version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: salary_mgmt_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salary_mgmt_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_test_data:
